// Official municipal boundaries; Node 18+. Run: node tools/build_bairros_rio.mjs
import { writeFile } from 'node:fs/promises';
const source = 'https://pgeo3.rio.rj.gov.br/arcgis/rest/services/Cartografia/Limites_administrativos/FeatureServer/4';
const censusSource = 'https://pgeo3.rio.rj.gov.br/arcgis/rest/services/Censo/Limites_administrativos_Censo_2022/MapServer/2';
const censusParams = new URLSearchParams({ where: '1=1', outFields: 'codbairro,nome,Total_de_pessoas_2022', returnGeometry: 'false', f: 'json' });
const censusResponse = await fetch(censusSource + '/query?' + censusParams);
if (!censusResponse.ok) throw new Error('Census HTTP ' + censusResponse.status);
const census = await censusResponse.json();
if (census.error || census.exceededTransferLimit || !census.features?.length) throw new Error('Incomplete census');
const populations = new Map(census.features.map(f => [Number(f.attributes.codbairro), f.attributes.Total_de_pessoas_2022]));
const params = new URLSearchParams({ where: '1=1', outFields: 'codbairro,nome,regiao_adm,Shape__Area', outSR: '4326', returnGeometry: 'true', geometryPrecision: '5', maxAllowableOffset: '0.00003', f: 'json' });
const response = await fetch(source + '/query?' + params);
if (!response.ok) throw new Error('HTTP ' + response.status);
const data = await response.json();
if (data.error || data.exceededTransferLimit || !data.features?.length) throw new Error(JSON.stringify(data.error || 'Incomplete dataset'));
const bairros = data.features.map(({ attributes: a, geometry: g }) => ({ id: a.codbairro, nome: a.nome, ra: a.regiao_adm, populacao: populations.get(Number(a.codbairro)) ?? null, area: a.Shape__Area / 1e6, aneis: g.rings }));
bairros.sort((a, b) => a.nome.localeCompare(b.nome, 'pt-BR'));
if (new Set(bairros.map(b => b.id)).size !== bairros.length || bairros.some(b => !b.nome || !b.aneis.length)) throw new Error('Invalid neighborhoods');
// Census geography still includes Argentino (166) within Brás de Pina (045).
// Fail closed on any new mismatch: never silently turn missing population into zero.
if (bairros.some(b => !(b.area > 0) || (b.populacao !== null && (!Number.isInteger(b.populacao) || b.populacao < 0)))) throw new Error('Invalid area/population');
const missing = bairros.filter(b => b.populacao === null).map(b => Number(b.id));
if (JSON.stringify(missing) !== '[166]' || !populations.has(45) || populations.size !== 165) throw new Error('Census geography changed: review population groups');
const metadata = { fonte: source, fontePopulacao: censusSource, anoPopulacao: 2022, versaoMetricas: 'censo2022-area202609-v1', gruposPopulacao: [{ ids: ['045', '166'], populacao: populations.get(45) }], consultadoEm: new Date().toISOString().slice(0, 10), total: bairros.length };
await writeFile(new URL('../data/bairros_rio.js', import.meta.url), '// Generated by tools/build_bairros_rio.mjs — Prefeitura do Rio / IPP.\nvar BAIRROS_RIO_META = ' + JSON.stringify(metadata) + ';\nvar BAIRROS_RIO = ' + JSON.stringify(bairros) + ';\n');
console.log(metadata);
