// Official municipal boundaries; Node 18+. Run: node tools/build_bairros_rio.mjs
import { writeFile } from 'node:fs/promises';
const source = 'https://pgeo3.rio.rj.gov.br/arcgis/rest/services/Cartografia/Limites_administrativos/FeatureServer/4';
const params = new URLSearchParams({ where: '1=1', outFields: 'codbairro,nome,regiao_adm', outSR: '4326', returnGeometry: 'true', geometryPrecision: '5', maxAllowableOffset: '0.00003', f: 'json' });
const response = await fetch(source + '/query?' + params);
if (!response.ok) throw new Error('HTTP ' + response.status);
const data = await response.json();
if (data.error || data.exceededTransferLimit || !data.features?.length) throw new Error(JSON.stringify(data.error || 'Incomplete dataset'));
const bairros = data.features.map(({ attributes: a, geometry: g }) => ({ id: a.codbairro, nome: a.nome, ra: a.regiao_adm, aneis: g.rings }));
bairros.sort((a, b) => a.nome.localeCompare(b.nome, 'pt-BR'));
if (new Set(bairros.map(b => b.id)).size !== bairros.length || bairros.some(b => !b.nome || !b.aneis.length)) throw new Error('Invalid neighborhoods');
const metadata = { fonte: source, consultadoEm: new Date().toISOString().slice(0, 10), total: bairros.length };
await writeFile(new URL('../data/bairros_rio.js', import.meta.url), '// Generated by tools/build_bairros_rio.mjs — Prefeitura do Rio / IPP.\nvar BAIRROS_RIO_META = ' + JSON.stringify(metadata) + ';\nvar BAIRROS_RIO = ' + JSON.stringify(bairros) + ';\n');
console.log(metadata);
